"""Drive the `lindhard` command for the level-2 and level-3 harness.

Standard library only. A *problem* is a plain dict (see
`validation/oracles/problems.json` for the schema); this module turns it into
a `lindhard` TOML input (schema: docs/cli.md), runs it, and reads back the
summary metrics from `summary.json`.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RUNS = REPO / "validation" / "oracle-runs"  # gitignored (CONTRIBUTING.md, Oracles)


def die(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(2)


def lindhard_binary() -> Path:
    """`$LINDHARD_BIN`, or the release binary built by cargo."""
    env = os.environ.get("LINDHARD_BIN")
    if env:
        return Path(env)
    proc = subprocess.run(
        ["cargo", "build", "--release", "-p", "lindhard-cli", "--message-format=json"],
        cwd=REPO,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    if proc.returncode != 0:
        die("`cargo build --release -p lindhard-cli` failed; run it by hand to see why")
    exe = None
    for line in proc.stdout.splitlines():
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            continue
        if msg.get("reason") == "compiler-artifact" and msg.get("executable"):
            if msg["target"]["name"] == "lindhard":
                exe = msg["executable"]
    if not exe:
        die("could not find the `lindhard` executable in cargo's build output")
    return Path(exe)


def version(binary: Path) -> str:
    out = subprocess.run([str(binary), "--version"], capture_output=True, text=True)
    return out.stdout.strip() or "unknown"


def _toml_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v)  # a TOML basic string is a JSON string for our keys
    raise TypeError(f"unsupported TOML value {v!r}")


def to_toml(problem: dict) -> str:
    """The `lindhard` input for a problem dict."""
    lines = ["# Generated by validation/lib/lindhard_cli.py; do not edit.", ""]

    def table(name: str, d: dict) -> None:
        lines.append(f"[{name}]")
        for k, v in d.items():
            lines.append(f"{k} = {_toml_value(v)}")
        lines.append("")

    table("beam", problem["beam"])
    table("target", {"substrate": problem["target"]["substrate"]})
    physics = dict(problem["physics"])
    energies = physics.pop("energies", {})
    table("physics", physics)
    for sym, e in energies.items():
        table(f"physics.energies.{sym}", e)
    table("run", problem["run"])
    table("tally", {**problem.get("tally", {}), "per_ion": False})
    return "\n".join(lines)


def run(problem: dict, workdir: Path, binary: Path | None = None) -> dict:
    """Run `lindhard` on a problem; return its summary metrics."""
    binary = binary or lindhard_binary()
    workdir.mkdir(parents=True, exist_ok=True)
    inp = workdir / "input.toml"
    inp.write_text(to_toml(problem))
    out = workdir / "out"
    proc = subprocess.run(
        [str(binary), "run", str(inp), "--out", str(out)],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        die(f"lindhard failed on {problem['id']}:\n{proc.stderr}")
    s = json.loads((out / "summary.json").read_text())
    r = s["results"]
    return {
        "code": "lindhard",
        "version": s["software"]["git_describe"],
        "ions": r["histories"],
        "rp_nm": r["primaries"]["stopped_depth_mean_nm"],
        "drp_nm": r["primaries"]["stopped_depth_std_nm"],
        "backscatter": r["yields"]["backscattered_per_ion"],
        "sputter_yield": r["yields"]["sputtered_per_ion"],
        "ions_per_s": s["run"]["ions_per_s"],
    }
