#!/usr/bin/env python3
"""Electron engine benchmarks on the matched problems of #150 (#152;
docs/benchmarks.md, "Electron engine"; CONTRIBUTING.md, "Oracles").

For each problem of `electron_problems.json` (electrons at normal incidence
into bulk Si and bulk Cu at 1, 5 and 20 keV) this script

1. writes lindhard's matched input from the user's cstool clone, exactly as
   `run_electron.py` does (same physics, same material files read at run
   time; into the gitignored `validation/oracle-runs/electron-bench/`);
2. runs `lindhard/examples/electron_scaling.rs` on it: the cross-section
   tables are built once and timed separately, then the same histories run on
   1, 2, ... N threads, each `--repeat` times; the example records wall time,
   electrons/s, speedup and parallel efficiency, and the SHA-256 of the full
   tally report at every thread count (it fails if they differ: determinism);
3. if Nebula is configured (the variables of `run_electron.py`), times
   Nebula's CPU build (`nebula_cpu_edep`, run unmodified, outside this tree)
   on the same primaries, with its deposit stream discarded;
4. writes one scalar summary per problem,
   `validation/oracles/summaries/bench-electron-<problem>.json`
   (format `lindhard-electron-bench/1`): versions, settings, host (CPU model
   and core counts, load average; no host name) and the timings. No oracle
   table, input or output is written there.

`--update-docs` rebuilds the electron tables of `docs/benchmarks.md` from the
committed summaries (this file's and #150's) without running anything.

Configuration (environment):

    CSTOOL_SRC      cstool clone (required; see run_electron.py)
    NEBULA_BIN, NEBULA_MATERIALS, NEBULA_SRC, NEBULA_VERSION, NEBULA_COMMIT,
    NEBULA_BUILD    as for run_electron.py (optional)
    LINDHARD_SCALING_BIN
                    the `electron_scaling` example binary; default: built
                    with `cargo build --release -p lindhard --example
                    electron_scaling` (CARGO_BUILD_JOBS limits the jobs)

Nebula's CPU driver starts one thread per hardware thread and has no option
to change that (source/cpu_energydep.cpp, std::thread::hardware_concurrency at
commit a50a8e8), so its timing is always at all logical CPUs; for a like-for-
like rate include that count in `--threads`. Its own "Simulation" time comes
from a progress loop that sleeps one second at a time, so it has a resolution
of about one second: use enough histories for runs of tens of seconds.

Benchmarks belong on a quiet machine. The summary records the load average at
the start and end of every problem; numbers taken under load are marked so in
the docs.

Usage:
    validation/oracles/bench_electron.py --threads 1,2,4 --repeat 3
    validation/oracles/bench_electron.py --problem e_5keV_si --scale 0.2 --lindhard-only
    validation/oracles/bench_electron.py --write-inputs      # inputs only (for the Criterion bench)
    validation/oracles/bench_electron.py --update-docs [--check]
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import platform
import re
import struct
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "lib"))
import lindhard_cli  # noqa: E402
import run_electron  # noqa: E402

FORMAT = "lindhard-electron-bench/1"
RUNS = lindhard_cli.RUNS / "electron-bench"
SUMMARIES = run_electron.SUMMARIES
DOC = lindhard_cli.REPO / "docs" / "benchmarks.md"
BEGIN = "<!-- electron-bench:begin (generated by validation/oracles/bench_electron.py --update-docs) -->"
END = "<!-- electron-bench:end -->"


# ---------------------------------------------------------------------------
# Host description (no host name, user or network identity)


def _cpu_model() -> str | None:
    if sys.platform.startswith("linux"):
        try:
            for line in Path("/proc/cpuinfo").read_text().splitlines():
                if line.startswith("model name"):
                    return line.split(":", 1)[1].strip()
        except OSError:
            return None
    if sys.platform == "darwin":
        out = subprocess.run(["sysctl", "-n", "machdep.cpu.brand_string"], capture_output=True, text=True)
        return out.stdout.strip() or None
    return None


def _physical_cores() -> int | None:
    if sys.platform.startswith("linux"):
        try:
            cores, phys, core = set(), None, None
            for line in Path("/proc/cpuinfo").read_text().splitlines():
                k, _, v = line.partition(":")
                k = k.strip()
                if k == "physical id":
                    phys = v.strip()
                elif k == "core id":
                    core = v.strip()
                elif not line.strip():
                    if core is not None:
                        cores.add((phys, core))
                    phys = core = None
            if core is not None:
                cores.add((phys, core))
            return len(cores) or None
        except OSError:
            return None
    if sys.platform == "darwin":
        out = subprocess.run(["sysctl", "-n", "hw.physicalcpu"], capture_output=True, text=True)
        return int(out.stdout) if out.stdout.strip().isdigit() else None
    return None


def load_average() -> float | None:
    return round(os.getloadavg()[0], 2) if hasattr(os, "getloadavg") else None


def host() -> dict:
    return {
        "system": platform.system(),
        "machine": platform.machine(),
        "cpu_model": _cpu_model(),
        "logical_cpus": os.cpu_count(),
        "physical_cores": _physical_cores(),
    }


# ---------------------------------------------------------------------------
# lindhard side


def scaling_binary() -> Path:
    env = os.environ.get("LINDHARD_SCALING_BIN")
    if env:
        return Path(env)
    proc = subprocess.run(
        ["cargo", "build", "--release", "-p", "lindhard", "--example", "electron_scaling",
         "--message-format=json"],
        cwd=lindhard_cli.REPO, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True,
    )
    if proc.returncode != 0:
        lindhard_cli.die("building the electron_scaling example failed; run the cargo command by hand")
    for line in proc.stdout.splitlines():
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            continue
        if msg.get("reason") == "compiler-artifact" and msg.get("executable") \
                and msg["target"]["name"] == "electron_scaling":
            return Path(msg["executable"])
    lindhard_cli.die("could not find the electron_scaling executable in cargo's output")
    raise AssertionError


def write_input(problem: dict, spec: dict, cstool: Path, histories: int) -> tuple[Path, dict]:
    """lindhard's matched input of `run_electron.py` for one problem, written to
    `RUNS/<problem>/input.toml` (the layout `LINDHARD_BENCH_ELECTRON_INPUTS`
    expects). Returns the path and the material note of the summary."""
    mat = run_electron.cstool_material(cstool, problem["cstool_material"])
    work = RUNS / problem["id"]
    work.mkdir(parents=True, exist_ok=True)
    elf = run_electron.write_elf(problem, mat, work)
    path = work / "input.toml"
    path.write_text(run_electron.lindhard_input(problem, spec, mat, elf, spec["seed"], histories))
    materials = {
        "cstool_source": "https://github.com/Nebula-simulator/cstool",
        "cstool_commit": run_electron._git(str(cstool), "rev-parse", "HEAD") or "unknown",
        "parameter_file": f"data/materials/{problem['cstool_material']}",
        "parameter_file_sha256": mat["yaml_sha256"],
        "elf_file": f"data/materials/{mat['df'].relative_to(mat['yaml'].parent)}",
        "elf_file_sha256": mat["df_sha256"],
    }
    return path, materials


def run_scaling(binary: Path, inp: Path, histories: int, threads: list[int], repeat: int,
                table_threads: int) -> dict:
    cmd = [str(binary), "--input", str(inp), "--histories", str(histories),
           "--threads", ",".join(map(str, threads)), "--repeat", str(repeat),
           "--table-threads", str(table_threads)]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode not in (0, 1) or not proc.stdout.strip():
        lindhard_cli.die(f"electron_scaling failed on {inp}:\n{proc.stderr}")
    out = json.loads(proc.stdout)
    for k in ("input", "problem"):
        out.pop(k, None)  # local paths
    return out


# ---------------------------------------------------------------------------
# Nebula side (timing only; the physics comparison is run_electron.py's)


def run_nebula(problem: dict, spec: dict, binary: Path, histories: int) -> dict:
    """Nebula's CPU build on the primaries and geometry of run_electron.py,
    with the deposit stream discarded (/dev/null), so that what is timed is the
    simulation and not our reading of its output. Returns process wall time,
    Nebula's own "Simulation" and loading times, and its version line."""
    neb = run_electron.Nebula()
    work = RUNS / "nebula" / problem["id"]
    work.mkdir(parents=True, exist_ok=True)
    tri = work / "geometry.tri"
    tri.write_text(neb.geometry())
    pri = work / "primaries.pri"
    rec = struct.Struct("=7f2i")
    with open(pri, "wb") as f:
        for i in range(histories):
            f.write(rec.pack(0.0, 0.0, neb.START_Z_NM, 0.0, 0.0, -1.0, problem["energy_ev"], i, 0))
    mat = Path(os.environ["NEBULA_MATERIALS"]) / problem["nebula_material"]
    if not mat.is_file():
        lindhard_cli.die(f"Nebula material file {mat} not found (NEBULA_MATERIALS)")
    log = work / "stderr.log"
    cmd = [str(binary), f"--seed={spec['seed']}", f"--detect-filename={work / 'detected.bin'}",
           f"--deposit-filename={os.devnull}", str(tri), str(pri), str(mat)]
    t0 = time.perf_counter()
    with open(log, "w") as err:
        proc = subprocess.run(cmd, cwd=work, stdout=subprocess.DEVNULL, stderr=err)
    wall = time.perf_counter() - t0
    if proc.returncode != 0:
        lindhard_cli.die(f"Nebula failed on {problem['id']} (exit {proc.returncode}); see {log}")
    text = log.read_text()
    timings = {m.group(1).strip(): float(m.group(2))
               for m in re.finditer(r"^\s*([A-Za-z ]+):\s*([0-9.]+)\s*$", text, re.M)}
    threads = re.search(r"Creating (\d+) CPU drivers", text)
    version = next((ln for ln in text.splitlines() if ln.startswith("This is Nebula version")), "")
    sim = timings.get("Simulation")
    return {
        "histories": histories,
        "threads": int(threads.group(1)) if threads else None,
        "process_wall_s": wall,
        "simulation_s": sim,
        "loading_materials_s": timings.get("Loading materials"),
        "electrons_per_s": histories / sim if sim else None,
        "nebula_reports": version.replace("This is ", "") or None,
        "material_file": problem["nebula_material"],
        "material_sha256": run_electron.sha256(mat),
    }


# ---------------------------------------------------------------------------
# docs/benchmarks.md


def _fmt(x, digits=3):
    if x is None:
        return "n/a"
    return f"{x:.{digits}g}"


def doc_tables() -> str:
    spec = json.loads(run_electron.PROBLEMS.read_text())
    order = [p["id"] for p in spec["problems"]]
    lines = []
    benches = sorted(SUMMARIES.glob("bench-electron-*.json"),
                     key=lambda p: order.index(p.stem.removeprefix("bench-electron-"))
                     if p.stem.removeprefix("bench-electron-") in order else 99)
    lines.append("**lindhard, thread scaling** (`bench-electron-<problem>.json`; transport only, tables "
                 "built once beforehand; median of the repeats; efficiency = speedup x 1 / threads).")
    lines.append("")
    lines.append("| Problem | Histories | Threads | Wall (s) | Electrons/s | Speedup | Efficiency | "
                 "Same report | Tables (s): elastic + inelastic | Load at start / end | Host, date |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|")
    pending = set()
    for path in benches:
        s = json.loads(path.read_text())
        h = s["host"]
        host_s = (f"{h.get('cpu_model') or h.get('machine')}, {h.get('physical_cores')} cores / "
                  f"{h.get('logical_cpus')} threads; {s['date']}")
        lin = s["lindhard"]
        tb = lin["tables"]
        measured = {r["threads"] for r in lin["runs"]}
        for r in lin["runs"]:
            lines.append(
                f"| `{s['problem']}` | {lin['histories']} | {r['threads']} | {_fmt(r['wall_s_median'])} | "
                f"{_fmt(r['electrons_per_s'])} | {_fmt(r['speedup'])} | {_fmt(r['efficiency'])} | "
                f"{'yes' if r['identical_to_first'] else '**no**'} | "
                f"{_fmt(tb['elastic_s'])} + {_fmt(tb['inelastic_s'])} | "
                f"{_fmt(s['load_average']['start'])} / {_fmt(s['load_average']['end'])} | {host_s} |")
        cores = h.get("physical_cores") or 0
        n = 1
        while n <= cores:
            if n not in measured:
                pending.add(n)
            n *= 2
        if cores and cores not in measured:
            pending.add(cores)
    if pending:
        lines.append("")
        lines.append("Not measured (placeholders, see the caveats below): "
                     + ", ".join(f"{n} threads" for n in sorted(pending))
                     + " on every problem.")
    lines.append("")

    nebs = [json.loads(p.read_text()) for p in benches]
    nebs = [s for s in nebs if s.get("nebula")]
    lines.append("**lindhard vs Nebula CPU, transport rate** (`bench-electron-<problem>.json`):")
    lines.append("")
    if nebs:
        lines.append("| Problem | Threads | lindhard electrons/s | Nebula electrons/s | Ratio (lindhard / Nebula) | "
                     "Nebula version | Load at start |")
        lines.append("|---|---|---|---|---|---|---|")
        for s in nebs:
            c = s.get("comparison") or {}
            lines.append(
                f"| `{s['problem']}` | {s['nebula']['threads']} | {_fmt(c.get('lindhard_electrons_per_s'))} | "
                f"{_fmt(s['nebula']['electrons_per_s'])} | {_fmt(c.get('electrons_per_s_ratio'))} | "
                f"{s['nebula'].get('version')} | {_fmt(s['load_average']['start'])} |")
    else:
        lines.append("Not measured yet: no `bench-electron-*.json` summary has a Nebula timing (see the caveats).")
    lines.append("")

    lines.append("**End-to-end wall time of the #150 comparison runs** (`nebula-<problem>.json`, `wall_s`; not "
                 "re-run here). lindhard: 10 batch processes, each building its tables and running a tenth of the "
                 "histories; Nebula: one process, material loading included, its deposit stream read by "
                 "`run_electron.py`. Not a transport-rate comparison.")
    lines.append("")
    lines.append("| Problem | Histories | lindhard wall (s) | Nebula wall (s) | Nebula end-to-end electrons/s | "
                 "Nebula version | Host, load at start, date |")
    lines.append("|---|---|---|---|---|---|---|")
    for pid in order:
        path = SUMMARIES / f"nebula-{pid}.json"
        if not path.is_file():
            continue
        s = json.loads(path.read_text())
        n = s["histories"]["oracle"]
        w = s["wall_s"]
        lines.append(f"| `{pid}` | {n} | {_fmt(w['lindhard'], 4)} | {_fmt(w['oracle'], 4)} | "
                     f"{_fmt(n / w['oracle'] if w['oracle'] else None)} | {s['oracle_version']} | "
                     f"{s['host']}, {s['date']} |")
    return "\n".join(lines)


def update_docs(check: bool = False) -> int:
    """Rewrite the block between the markers; with `check`, only compare."""
    text = DOC.read_text()
    if BEGIN not in text or END not in text:
        lindhard_cli.die(f"{DOC}: markers not found")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + BEGIN + "\n" + doc_tables() + "\n" + END + tail
    if check:
        if new != text:
            print(f"{DOC.relative_to(lindhard_cli.REPO)} is out of date: run "
                  "validation/oracles/bench_electron.py --update-docs", file=sys.stderr)
            return 1
        return 0
    DOC.write_text(new)
    print(f"updated {DOC.relative_to(lindhard_cli.REPO)}")
    return 0


# ---------------------------------------------------------------------------


def _round(x):
    return run_electron._round(x)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--problem", action="append", help="problem id (repeatable)")
    ap.add_argument("--threads", help="thread counts, e.g. 1,2,4 (default: 1, 2, 4, ... up to the physical cores)")
    ap.add_argument("--repeat", type=int, default=3, help="transport runs per thread count (median reported)")
    ap.add_argument("--table-threads", type=int, default=1, help="threads of the table build")
    ap.add_argument("--scale", type=float, default=1.0, help="multiply every history count")
    ap.add_argument("--lindhard-only", action="store_true", help="do not time Nebula")
    ap.add_argument("--write-inputs", action="store_true", help="write the matched inputs and stop")
    ap.add_argument("--update-docs", action="store_true", help="rebuild the docs tables and stop")
    ap.add_argument("--check", action="store_true",
                    help="with --update-docs: exit 1 if the docs differ, write nothing (CI)")
    args = ap.parse_args()

    if args.update_docs:
        return update_docs(check=args.check)

    spec = json.loads(run_electron.PROBLEMS.read_text())
    problems = [p for p in spec["problems"] if not args.problem or p["id"] in args.problem]
    if not problems:
        lindhard_cli.die(f"no problem matches {args.problem}")
    src = os.environ.get("CSTOOL_SRC")
    if not src:
        print("CSTOOL_SRC not set: the material parameters come from cstool's files (see run_electron.py); "
              "nothing run")
        return 0
    cstool = Path(src)

    h = host()
    if args.threads:
        threads = [int(t) for t in args.threads.split(",")]
    else:
        cores = h["physical_cores"] or h["logical_cpus"] or 1
        threads, n = [], 1
        while n < cores:
            threads.append(n)
            n *= 2
        threads.append(cores)

    if args.write_inputs:
        for p in problems:
            path, _ = write_input(p, spec, cstool, p["histories"])
            print(f"wrote {path}")
        print(f"LINDHARD_BENCH_ELECTRON_INPUTS={RUNS}")
        return 0

    nebula = None
    if not args.lindhard_only:
        try:
            b = run_electron.Nebula().binary()
            nebula = (b, run_electron.Nebula().version(b))
            print(f"Nebula: {b} ({nebula[1]})")
            if (os.cpu_count() or 0) not in threads:
                print(f"note: Nebula runs on {os.cpu_count()} threads; add that count to --threads "
                      "for a like-for-like rate")
        except run_electron.NotConfigured as e:
            print(e)

    binary = scaling_binary()
    version = _version()
    rustc = subprocess.run(["rustc", "--version"], capture_output=True, text=True).stdout.strip() or None
    today = _dt.date.today().isoformat()
    SUMMARIES.mkdir(exist_ok=True)
    for p in problems:
        n = max(spec["batches"], int(round(p["histories"] * args.scale)))
        inp, materials = write_input(p, spec, cstool, n)
        load0 = load_average()
        lin = run_scaling(binary, inp, n, threads, args.repeat, args.table_threads)
        neb = run_nebula(p, spec, nebula[0], n) if nebula else None
        load1 = load_average()
        for r in lin["runs"]:
            print(f"{p['id']}: {r['threads']} threads, {r['electrons_per_s']:.4g} electrons/s, "
                  f"efficiency {r['efficiency']:.3f}, same report {r['identical_to_first']}")
        comparison = None
        if neb:
            neb.update({"version": nebula[1], "commit": run_electron.Nebula().commit(),
                        "build": run_electron.Nebula().build(),
                        "source": run_electron.Nebula.source_url,
                        "license": run_electron.Nebula.license_note})
            same = next((r for r in lin["runs"] if r["threads"] == neb["threads"]), None)
            comparison = {
                "threads": neb["threads"],
                "lindhard_electrons_per_s": same["electrons_per_s"] if same else None,
                "nebula_electrons_per_s": neb["electrons_per_s"],
                "electrons_per_s_ratio": (same["electrons_per_s"] / neb["electrons_per_s"]
                                          if same and neb["electrons_per_s"] else None),
                "note": "> 1: lindhard faster; transport only on both sides (lindhard after its table build, "
                        "Nebula's own Simulation time after loading its cstool material file)",
            }
            print(f"  Nebula: {neb['threads']} threads, {_fmt(neb['electrons_per_s'])} electrons/s")
        summary = {
            "format": FORMAT,
            "problem": p["id"],
            "date": today,
            "lindhard_version": version,
            "build": {"profile": "release (lto = fat, codegen-units = 1)", "rustc": rustc},
            "host": h,
            "load_average": {"start": load0, "end": load1},
            "materials": materials,
            "settings": {
                "energy_ev": p["energy_ev"],
                "element": p["element"],
                "seed": spec["seed"],
                "physics": spec["lindhard"],
                "tally": {"se_bse_split_ev": spec["split_ev"], "rmax_nm": p["rmax_nm"], "rbins": p["rbins"]},
            },
            "lindhard": lin,
            "nebula": neb,
            "comparison": comparison,
            "caveats": [
                "timings depend on the hardware, the build (compiler, flags) and the load of the machine; "
                "compare ratios within one summary, not absolute numbers across machines",
                "the physics differs between the codes (run_electron.py mismatches: full vs single-pole Penn, "
                "ELSEPA vs Thomas-Fermi Yukawa Mott, phonon and recoil losses), so the work per history differs",
                "Nebula always runs on all logical CPUs (no thread option)",
            ],
        }
        path = SUMMARIES / f"bench-electron-{p['id']}.json"
        path.write_text(json.dumps(_round(summary), indent=2, ensure_ascii=False) + "\n")
        print(f"  wrote {path.relative_to(lindhard_cli.REPO)}")
        if not lin["deterministic"]:
            lindhard_cli.die(f"{p['id']}: the tally report differs between thread counts")
    return 0


def _version() -> str:
    """`lindhard <workspace version> (<git describe>)`, as `lindhard --version`."""
    m = re.search(r'^version = "([^"]+)"', (lindhard_cli.REPO / "Cargo.toml").read_text(), re.M)
    d = run_electron._git(str(lindhard_cli.REPO), "describe", "--always", "--dirty")
    return f"lindhard {m.group(1) if m else '?'} ({d or 'unknown'})"


if __name__ == "__main__":
    sys.exit(main())
